# -*- coding: utf-8 -*-
"""16_CarPricePredictionusing_RANDOMFOREST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KK8gbJzTCV0aYPl6UssmwXXMzwgQxUHB

# **Day-16 | Car Price Prediction using RANDOM FOREST**
"""

import pandas as pd

"""# *Load Dataset from Local directory*"""

from google.colab import files
uploaded = files.upload()

"""# *Load Dataset*"""

dataset = pd.read_csv('dataset.csv')
dataset = dataset.drop(['car_ID'],axis=1)

"""### *Summarize Dataset*"""

print(dataset.shape)
print(dataset.head(5))

"""### *Splitting Dataset into X & Y*
### *This X contains Both Numerical & Text Data*
"""

Xdata = dataset.drop('price',axis='columns')
numericalCols=Xdata.select_dtypes(exclude=['object']).columns
X=Xdata[numericalCols]
X

Y = dataset['price']
Y

"""### *Scaling the Independent Variables (Features)*"""

from sklearn.preprocessing import scale
cols = X.columns
X = pd.DataFrame(scale(X))
X.columns = cols
X

"""### *Splitting Dataset into Train & Test*"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.20,random_state=0)

"""### *Training using Random Forest*"""

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train, y_train)

"""### *Evaluating Model*"""

ypred = model.predict(x_test)

from sklearn.metrics import r2_score
r2score = r2_score(y_test,ypred)
print("R2Score",r2score*100)